# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_DescargasYEscaneoArchivos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DescargaEscaneoArchivos(object):
    def setupUi(self, DescargaEscaneoArchivos):
        DescargaEscaneoArchivos.setObjectName("DescargaEscaneoArchivos")
        DescargaEscaneoArchivos.resize(338, 238)
        self.widget = QtWidgets.QWidget(DescargaEscaneoArchivos)
        self.widget.setGeometry(QtCore.QRect(30, 20, 281, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_descarando_archivos = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_descarando_archivos.setFont(font)
        self.lbl_descarando_archivos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_descarando_archivos.setObjectName("lbl_descarando_archivos")
        self.verticalLayout.addWidget(self.lbl_descarando_archivos)
        self.pgr_descarga_archivo = QtWidgets.QProgressBar(self.widget)
        self.pgr_descarga_archivo.setProperty("value", 0)
        self.pgr_descarga_archivo.setObjectName("pgr_descarga_archivo")
        self.verticalLayout.addWidget(self.pgr_descarga_archivo)
        spacerItem = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_buscando_amenazas = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_buscando_amenazas.setFont(font)
        self.lbl_buscando_amenazas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_buscando_amenazas.setObjectName("lbl_buscando_amenazas")
        self.verticalLayout.addWidget(self.lbl_buscando_amenazas)
        self.pgr_escaneo_amenazas = QtWidgets.QProgressBar(self.widget)
        self.pgr_escaneo_amenazas.setProperty("value", 0)
        self.pgr_escaneo_amenazas.setObjectName("pgr_escaneo_amenazas")
        self.verticalLayout.addWidget(self.pgr_escaneo_amenazas)

        self.retranslateUi(DescargaEscaneoArchivos)
        QtCore.QMetaObject.connectSlotsByName(DescargaEscaneoArchivos)

    def retranslateUi(self, DescargaEscaneoArchivos):
        _translate = QtCore.QCoreApplication.translate
        DescargaEscaneoArchivos.setWindowTitle(_translate("DescargaEscaneoArchivos", "Descarga y Escaneo de amenazas"))
        self.lbl_descarando_archivos.setText(_translate("DescargaEscaneoArchivos", "Descargando archivos ..."))
        self.lbl_buscando_amenazas.setText(_translate("DescargaEscaneoArchivos", "Buscando amenazas ..."))
