# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_DescargaArchivos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_DescargaArchivo(object):
    def setupUi(self, Dialogo_DescargaArchivo):
        Dialogo_DescargaArchivo.setObjectName("Dialogo_DescargaArchivo")
        Dialogo_DescargaArchivo.resize(398, 172)
        self.lbl_descarga = QtWidgets.QLabel(Dialogo_DescargaArchivo)
        self.lbl_descarga.setGeometry(QtCore.QRect(30, 30, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_descarga.setFont(font)
        self.lbl_descarga.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_descarga.setObjectName("lbl_descarga")
        self.pbr_descarga_archivo = QtWidgets.QProgressBar(Dialogo_DescargaArchivo)
        self.pbr_descarga_archivo.setGeometry(QtCore.QRect(30, 80, 341, 23))
        self.pbr_descarga_archivo.setProperty("value", 0)
        self.pbr_descarga_archivo.setObjectName("pbr_descarga_archivo")

        self.retranslateUi(Dialogo_DescargaArchivo)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_DescargaArchivo)

    def retranslateUi(self, Dialogo_DescargaArchivo):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_DescargaArchivo.setWindowTitle(_translate("Dialogo_DescargaArchivo", "Descarga archivo"))
        self.lbl_descarga.setText(_translate("Dialogo_DescargaArchivo", "Descargando archivo..."))
