# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_EditorGrafico.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditorGrafico(object):
    def setupUi(self, EditorGrafico):
        EditorGrafico.setObjectName("EditorGrafico")
        EditorGrafico.resize(502, 257)
        self.centralwidget = QtWidgets.QWidget(EditorGrafico)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_estado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_estado.setGeometry(QtCore.QRect(30, 100, 421, 16))
        self.lbl_estado.setText("")
        self.lbl_estado.setObjectName("lbl_estado")
        EditorGrafico.setCentralWidget(self.centralwidget)
        self.mbr_principal = QtWidgets.QMenuBar(EditorGrafico)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 502, 21))
        self.mbr_principal.setObjectName("mbr_principal")
        self.mnu_dibujar = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_dibujar.setObjectName("mnu_dibujar")
        self.mnu_propiedades = QtWidgets.QMenu(self.mnu_dibujar)
        self.mnu_propiedades.setObjectName("mnu_propiedades")
        self.mnu_editar = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_editar.setObjectName("mnu_editar")
        EditorGrafico.setMenuBar(self.mbr_principal)
        self.statusbar = QtWidgets.QStatusBar(EditorGrafico)
        self.statusbar.setObjectName("statusbar")
        EditorGrafico.setStatusBar(self.statusbar)
        self.mni_Copiar = QtWidgets.QAction(EditorGrafico)
        self.mni_Copiar.setObjectName("mni_Copiar")
        self.mni_cortar = QtWidgets.QAction(EditorGrafico)
        self.mni_cortar.setObjectName("mni_cortar")
        self.mni_pegar = QtWidgets.QAction(EditorGrafico)
        self.mni_pegar.setObjectName("mni_pegar")
        self.mni_dibujar_circulo = QtWidgets.QAction(EditorGrafico)
        self.mni_dibujar_circulo.setObjectName("mni_dibujar_circulo")
        self.mni_dibujar_rectangulo = QtWidgets.QAction(EditorGrafico)
        self.mni_dibujar_rectangulo.setObjectName("mni_dibujar_rectangulo")
        self.mni_dibujar_linea = QtWidgets.QAction(EditorGrafico)
        self.mni_dibujar_linea.setObjectName("mni_dibujar_linea")
        self.mni_password = QtWidgets.QAction(EditorGrafico)
        self.mni_password.setObjectName("mni_password")
        self.mni_configurar_pagina = QtWidgets.QAction(EditorGrafico)
        self.mni_configurar_pagina.setObjectName("mni_configurar_pagina")
        self.mnu_propiedades.addAction(self.mni_password)
        self.mnu_propiedades.addAction(self.mni_configurar_pagina)
        self.mnu_dibujar.addAction(self.mni_dibujar_circulo)
        self.mnu_dibujar.addAction(self.mni_dibujar_rectangulo)
        self.mnu_dibujar.addAction(self.mni_dibujar_linea)
        self.mnu_dibujar.addSeparator()
        self.mnu_dibujar.addAction(self.mnu_propiedades.menuAction())
        self.mnu_editar.addAction(self.mni_Copiar)
        self.mnu_editar.addAction(self.mni_cortar)
        self.mnu_editar.addAction(self.mni_pegar)
        self.mbr_principal.addAction(self.mnu_dibujar.menuAction())
        self.mbr_principal.addAction(self.mnu_editar.menuAction())

        self.retranslateUi(EditorGrafico)
        QtCore.QMetaObject.connectSlotsByName(EditorGrafico)

    def retranslateUi(self, EditorGrafico):
        _translate = QtCore.QCoreApplication.translate
        EditorGrafico.setWindowTitle(_translate("EditorGrafico", "Editor Grafico"))
        self.mnu_dibujar.setTitle(_translate("EditorGrafico", "Dibujar"))
        self.mnu_propiedades.setTitle(_translate("EditorGrafico", "Propiedades"))
        self.mnu_editar.setTitle(_translate("EditorGrafico", "Editar"))
        self.mni_Copiar.setText(_translate("EditorGrafico", "Copiar"))
        self.mni_Copiar.setShortcut(_translate("EditorGrafico", "Ctrl+C"))
        self.mni_cortar.setText(_translate("EditorGrafico", "Cortar"))
        self.mni_cortar.setShortcut(_translate("EditorGrafico", "Ctrl+X"))
        self.mni_pegar.setText(_translate("EditorGrafico", "Pegar"))
        self.mni_pegar.setShortcut(_translate("EditorGrafico", "Ctrl+V"))
        self.mni_dibujar_circulo.setText(_translate("EditorGrafico", "Dibujar &Circulo"))
        self.mni_dibujar_circulo.setShortcut(_translate("EditorGrafico", "Shift+C"))
        self.mni_dibujar_rectangulo.setText(_translate("EditorGrafico", "Dibujar Rectangulo"))
        self.mni_dibujar_rectangulo.setShortcut(_translate("EditorGrafico", "Shift+R"))
        self.mni_dibujar_linea.setText(_translate("EditorGrafico", "Dibujar Linea"))
        self.mni_dibujar_linea.setShortcut(_translate("EditorGrafico", "Shift+L"))
        self.mni_password.setText(_translate("EditorGrafico", "Establecer contraseña"))
        self.mni_password.setShortcut(_translate("EditorGrafico", "Ctrl+T"))
        self.mni_configurar_pagina.setText(_translate("EditorGrafico", "Configurar página"))
        self.mni_configurar_pagina.setShortcut(_translate("EditorGrafico", "Ctrl+P"))
