# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MDI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(10, 10, 551, 431))
        self.mdiArea.setObjectName("mdiArea")
        self.win_primera_subventana = QtWidgets.QWidget()
        self.win_primera_subventana.setObjectName("win_primera_subventana")
        self.lbl_primera_subventana = QtWidgets.QLabel(self.win_primera_subventana)
        self.lbl_primera_subventana.setGeometry(QtCore.QRect(30, 150, 121, 16))
        self.lbl_primera_subventana.setObjectName("lbl_primera_subventana")
        self.win_segunda_subventana = QtWidgets.QWidget()
        self.win_segunda_subventana.setObjectName("win_segunda_subventana")
        self.lbl_segunda_subventana = QtWidgets.QLabel(self.win_segunda_subventana)
        self.lbl_segunda_subventana.setGeometry(QtCore.QRect(50, 150, 121, 16))
        self.lbl_segunda_subventana.setObjectName("lbl_segunda_subventana")
        MainWindow.setCentralWidget(self.centralwidget)
        self.mbr_principal = QtWidgets.QMenuBar(MainWindow)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.mbr_principal.setObjectName("mbr_principal")
        self.mnu_ventana = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_ventana.setObjectName("mnu_ventana")
        MainWindow.setMenuBar(self.mbr_principal)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mni_tabs = QtWidgets.QAction(MainWindow)
        self.mni_tabs.setObjectName("mni_tabs")
        self.mni_cascadas = QtWidgets.QAction(MainWindow)
        self.mni_cascadas.setObjectName("mni_cascadas")
        self.mni_cuadricula = QtWidgets.QAction(MainWindow)
        self.mni_cuadricula.setObjectName("mni_cuadricula")
        self.mni_subventana = QtWidgets.QAction(MainWindow)
        self.mni_subventana.setObjectName("mni_subventana")
        self.mnu_ventana.addAction(self.mni_tabs)
        self.mnu_ventana.addAction(self.mni_cascadas)
        self.mnu_ventana.addAction(self.mni_cuadricula)
        self.mnu_ventana.addAction(self.mni_subventana)
        self.mbr_principal.addAction(self.mnu_ventana.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana principal"))
        self.win_primera_subventana.setWindowTitle(_translate("MainWindow", "Primera subventana"))
        self.lbl_primera_subventana.setText(_translate("MainWindow", "Primera subventana"))
        self.win_segunda_subventana.setWindowTitle(_translate("MainWindow", "Segunda subventana"))
        self.lbl_segunda_subventana.setText(_translate("MainWindow", "Segunda subventana"))
        self.mnu_ventana.setTitle(_translate("MainWindow", "Ventanas"))
        self.mni_tabs.setText(_translate("MainWindow", "Vista Pestañas"))
        self.mni_cascadas.setText(_translate("MainWindow", "Vista Cascada"))
        self.mni_cuadricula.setText(_translate("MainWindow", "Vista Cuadrícula"))
        self.mni_subventana.setText(_translate("MainWindow", "Vista Subventana"))
