# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoVentaCamisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoVentaCamisa(object):
    def setupUi(self, DialogoVentaCamisa):
        DialogoVentaCamisa.setObjectName("DialogoVentaCamisa")
        DialogoVentaCamisa.resize(338, 486)
        self.lbl_selecciona_talle_de_camisa = QtWidgets.QLabel(DialogoVentaCamisa)
        self.lbl_selecciona_talle_de_camisa.setGeometry(QtCore.QRect(40, 40, 291, 16))
        self.lbl_selecciona_talle_de_camisa.setObjectName("lbl_selecciona_talle_de_camisa")
        self.verticalLayoutWidget = QtWidgets.QWidget(DialogoVentaCamisa)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 70, 160, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vly_talle_camisa = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vly_talle_camisa.setContentsMargins(0, 0, 0, 0)
        self.vly_talle_camisa.setObjectName("vly_talle_camisa")
        self.rbn_talla_l = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_l.setObjectName("rbn_talla_l")
        self.vly_talle_camisa.addWidget(self.rbn_talla_l)
        self.rbn_talla_m = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_m.setObjectName("rbn_talla_m")
        self.vly_talle_camisa.addWidget(self.rbn_talla_m)
        self.rbn_talla_xl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_xl.setObjectName("rbn_talla_xl")
        self.vly_talle_camisa.addWidget(self.rbn_talla_xl)
        self.rbn_talla_xxl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbn_talla_xxl.setObjectName("rbn_talla_xxl")
        self.vly_talle_camisa.addWidget(self.rbn_talla_xxl)
        self.lbl_selecciona_metodo_de_pago = QtWidgets.QLabel(DialogoVentaCamisa)
        self.lbl_selecciona_metodo_de_pago.setGeometry(QtCore.QRect(40, 200, 221, 16))
        self.lbl_selecciona_metodo_de_pago.setObjectName("lbl_selecciona_metodo_de_pago")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(DialogoVentaCamisa)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 240, 201, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vly_metodo_pago = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vly_metodo_pago.setContentsMargins(0, 0, 0, 0)
        self.vly_metodo_pago.setObjectName("vly_metodo_pago")
        self.rbn_tarjeta_debito_credito = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_tarjeta_debito_credito.setObjectName("rbn_tarjeta_debito_credito")
        self.vly_metodo_pago.addWidget(self.rbn_tarjeta_debito_credito)
        self.rbn_contraentrega = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_contraentrega.setObjectName("rbn_contraentrega")
        self.vly_metodo_pago.addWidget(self.rbn_contraentrega)
        self.rbn_consignacion_bancaria = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rbn_consignacion_bancaria.setObjectName("rbn_consignacion_bancaria")
        self.vly_metodo_pago.addWidget(self.rbn_consignacion_bancaria)
        self.lbl_mostrar_resultado = QtWidgets.QLabel(DialogoVentaCamisa)
        self.lbl_mostrar_resultado.setGeometry(QtCore.QRect(40, 340, 251, 16))
        self.lbl_mostrar_resultado.setText("")
        self.lbl_mostrar_resultado.setObjectName("lbl_mostrar_resultado")

        self.retranslateUi(DialogoVentaCamisa)
        QtCore.QMetaObject.connectSlotsByName(DialogoVentaCamisa)

    def retranslateUi(self, DialogoVentaCamisa):
        _translate = QtCore.QCoreApplication.translate
        DialogoVentaCamisa.setWindowTitle(_translate("DialogoVentaCamisa", "Venta Camisa"))
        self.lbl_selecciona_talle_de_camisa.setText(_translate("DialogoVentaCamisa", "Escoja el talle de la camisa"))
        self.rbn_talla_l.setText(_translate("DialogoVentaCamisa", "Talla L"))
        self.rbn_talla_m.setText(_translate("DialogoVentaCamisa", "Talla M"))
        self.rbn_talla_xl.setText(_translate("DialogoVentaCamisa", "Talla XL"))
        self.rbn_talla_xxl.setText(_translate("DialogoVentaCamisa", "Talla XXL"))
        self.lbl_selecciona_metodo_de_pago.setText(_translate("DialogoVentaCamisa", "Selecciona el método de pago:"))
        self.rbn_tarjeta_debito_credito.setText(_translate("DialogoVentaCamisa", "Tarjerta Débito/Crédito"))
        self.rbn_contraentrega.setText(_translate("DialogoVentaCamisa", "Pago contraentrega"))
        self.rbn_consignacion_bancaria.setText(_translate("DialogoVentaCamisa", "Consignación bancaria"))
