# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoSaludo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_saludar(object):
    def setupUi(self, Dialogo_saludar):
        Dialogo_saludar.setObjectName("Dialogo_saludar")
        Dialogo_saludar.resize(377, 193)
        self.lbl_escriba_nombre = QtWidgets.QLabel(Dialogo_saludar)
        self.lbl_escriba_nombre.setGeometry(QtCore.QRect(40, 30, 121, 16))
        self.lbl_escriba_nombre.setObjectName("lbl_escriba_nombre")
        self.txt_nombre = QtWidgets.QLineEdit(Dialogo_saludar)
        self.txt_nombre.setGeometry(QtCore.QRect(180, 30, 171, 22))
        self.txt_nombre.setObjectName("txt_nombre")
        self.lbl_saludo = QtWidgets.QLabel(Dialogo_saludar)
        self.lbl_saludo.setGeometry(QtCore.QRect(40, 90, 61, 16))
        self.lbl_saludo.setObjectName("lbl_saludo")
        self.lbl_mensaje_saludo = QtWidgets.QLabel(Dialogo_saludar)
        self.lbl_mensaje_saludo.setGeometry(QtCore.QRect(130, 90, 221, 20))
        self.lbl_mensaje_saludo.setText("")
        self.lbl_mensaje_saludo.setObjectName("lbl_mensaje_saludo")
        self.btn_saludar = QtWidgets.QPushButton(Dialogo_saludar)
        self.btn_saludar.setGeometry(QtCore.QRect(180, 130, 171, 24))
        self.btn_saludar.setObjectName("btn_saludar")

        self.retranslateUi(Dialogo_saludar)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_saludar)

    def retranslateUi(self, Dialogo_saludar):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_saludar.setWindowTitle(_translate("Dialogo_saludar", "Dialogo Saludo"))
        self.lbl_escriba_nombre.setText(_translate("Dialogo_saludar", "Escribe tu nombre:"))
        self.lbl_saludo.setText(_translate("Dialogo_saludar", "Saludo:"))
        self.btn_saludar.setText(_translate("Dialogo_saludar", "Saludar"))
