# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_copiar_y_pegar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 260)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 211, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 190, 211, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btn_copiar = QtWidgets.QPushButton(Dialog)
        self.btn_copiar.setGeometry(QtCore.QRect(70, 70, 191, 24))
        self.btn_copiar.setObjectName("btn_copiar")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 150, 181, 24))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        self.btn_copiar.pressed.connect(self.lineEdit.selectAll)
        self.btn_copiar.released.connect(self.lineEdit.copy)
        self.pushButton_2.clicked.connect(self.lineEdit_2.paste)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_copiar.setText(_translate("Dialog", "Seleccionar y copiar"))
        self.pushButton_2.setText(_translate("Dialog", "Pegar del portapapeles"))
