# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoHeladerias.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoHeladera(object):
    def setupUi(self, DialogoHeladera):
        DialogoHeladera.setObjectName("DialogoHeladera")
        DialogoHeladera.resize(400, 300)
        self.gbx_sabores = QtWidgets.QGroupBox(DialogoHeladera)
        self.gbx_sabores.setGeometry(QtCore.QRect(30, 50, 120, 80))
        self.gbx_sabores.setCheckable(True)
        self.gbx_sabores.setChecked(True)
        self.gbx_sabores.setObjectName("gbx_sabores")
        self.chk_chocolate = QtWidgets.QCheckBox(self.gbx_sabores)
        self.chk_chocolate.setGeometry(QtCore.QRect(10, 20, 77, 20))
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.chk_crema = QtWidgets.QCheckBox(self.gbx_sabores)
        self.chk_crema.setGeometry(QtCore.QRect(10, 50, 77, 20))
        self.chk_crema.setObjectName("chk_crema")
        self.lbl_heladeria = QtWidgets.QLabel(DialogoHeladera)
        self.lbl_heladeria.setGeometry(QtCore.QRect(80, 20, 211, 20))
        self.lbl_heladeria.setObjectName("lbl_heladeria")

        self.retranslateUi(DialogoHeladera)
        QtCore.QMetaObject.connectSlotsByName(DialogoHeladera)

    def retranslateUi(self, DialogoHeladera):
        _translate = QtCore.QCoreApplication.translate
        DialogoHeladera.setWindowTitle(_translate("DialogoHeladera", "DialogoHeladería"))
        self.gbx_sabores.setTitle(_translate("DialogoHeladera", "Sabores:"))
        self.chk_chocolate.setText(_translate("DialogoHeladera", "Chocolate"))
        self.chk_crema.setText(_translate("DialogoHeladera", "Creama"))
        self.lbl_heladeria.setText(_translate("DialogoHeladera", "Heladería de los mil sabores..."))
