# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoEventos_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventoDialogo(object):
    def setupUi(self, EventoDialogo):
        EventoDialogo.setObjectName("EventoDialogo")
        EventoDialogo.resize(400, 300)
        self.txt_caja = QtWidgets.QLineEdit(EventoDialogo)
        self.txt_caja.setGeometry(QtCore.QRect(120, 40, 113, 22))
        self.txt_caja.setObjectName("txt_caja")
        self.btn_limpiar = QtWidgets.QPushButton(EventoDialogo)
        self.btn_limpiar.setGeometry(QtCore.QRect(140, 180, 75, 24))
        self.btn_limpiar.setObjectName("btn_limpiar")

        self.retranslateUi(EventoDialogo)
        self.btn_limpiar.clicked.connect(self.txt_caja.clear())
        QtCore.QMetaObject.connectSlotsByName(EventoDialogo)

    def retranslateUi(self, EventoDialogo):
        _translate = QtCore.QCoreApplication.translate
        EventoDialogo.setWindowTitle(_translate("EventoDialogo", "Eventos en PyQt  - 1"))
        self.btn_limpiar.setText(_translate("EventoDialogo", "PushButton"))
