# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoClaseVuelo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogoClaseVuelo(object):
    def setupUi(self, DialogoClaseVuelo):
        DialogoClaseVuelo.setObjectName("DialogoClaseVuelo")
        DialogoClaseVuelo.resize(400, 207)
        self.lbl_escoja_un_vuelo = QtWidgets.QLabel(DialogoClaseVuelo)
        self.lbl_escoja_un_vuelo.setGeometry(QtCore.QRect(30, 30, 231, 16))
        self.lbl_escoja_un_vuelo.setObjectName("lbl_escoja_un_vuelo")
        self.rbn_primera_clase = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_primera_clase.setGeometry(QtCore.QRect(30, 60, 141, 20))
        self.rbn_primera_clase.setObjectName("rbn_primera_clase")
        self.rbn_segunda_clase = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_segunda_clase.setGeometry(QtCore.QRect(30, 90, 141, 20))
        self.rbn_segunda_clase.setObjectName("rbn_segunda_clase")
        self.rbn_tercera_clase = QtWidgets.QRadioButton(DialogoClaseVuelo)
        self.rbn_tercera_clase.setGeometry(QtCore.QRect(30, 120, 141, 20))
        self.rbn_tercera_clase.setObjectName("rbn_tercera_clase")
        self.lbl_resultado_seleccion = QtWidgets.QLabel(DialogoClaseVuelo)
        self.lbl_resultado_seleccion.setGeometry(QtCore.QRect(30, 160, 301, 16))
        self.lbl_resultado_seleccion.setText("")
        self.lbl_resultado_seleccion.setObjectName("lbl_resultado_seleccion")

        self.retranslateUi(DialogoClaseVuelo)
        QtCore.QMetaObject.connectSlotsByName(DialogoClaseVuelo)

    def retranslateUi(self, DialogoClaseVuelo):
        _translate = QtCore.QCoreApplication.translate
        DialogoClaseVuelo.setWindowTitle(_translate("DialogoClaseVuelo", "Dialog"))
        self.lbl_escoja_un_vuelo.setText(_translate("DialogoClaseVuelo", "Escoja la clase de vuelo:"))
        self.rbn_primera_clase.setText(_translate("DialogoClaseVuelo", "Primera clase"))
        self.rbn_segunda_clase.setText(_translate("DialogoClaseVuelo", "Segunda Clase"))
        self.rbn_tercera_clase.setText(_translate("DialogoClaseVuelo", "Tercera clase"))
