# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_CreacionTabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_CreacionTabla(object):
    def setupUi(self, Dialogo_CreacionTabla):
        Dialogo_CreacionTabla.setObjectName("Dialogo_CreacionTabla")
        Dialogo_CreacionTabla.resize(465, 319)
        self.lbl_nombre_base_datos = QtWidgets.QLabel(Dialogo_CreacionTabla)
        self.lbl_nombre_base_datos.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.lbl_nombre_base_datos.setObjectName("lbl_nombre_base_datos")
        self.lbl_nombre_tabla = QtWidgets.QLabel(Dialogo_CreacionTabla)
        self.lbl_nombre_tabla.setGeometry(QtCore.QRect(40, 80, 141, 16))
        self.lbl_nombre_tabla.setObjectName("lbl_nombre_tabla")
        self.txt_nombre_base_datos = QtWidgets.QLineEdit(Dialogo_CreacionTabla)
        self.txt_nombre_base_datos.setGeometry(QtCore.QRect(220, 40, 221, 20))
        self.txt_nombre_base_datos.setObjectName("txt_nombre_base_datos")
        self.txt_nombre_tabla = QtWidgets.QLineEdit(Dialogo_CreacionTabla)
        self.txt_nombre_tabla.setGeometry(QtCore.QRect(220, 80, 221, 20))
        self.txt_nombre_tabla.setObjectName("txt_nombre_tabla")
        self.gbx_columnas = QtWidgets.QGroupBox(Dialogo_CreacionTabla)
        self.gbx_columnas.setGeometry(QtCore.QRect(30, 130, 411, 91))
        self.gbx_columnas.setObjectName("gbx_columnas")
        self.txt_nombre_columna = QtWidgets.QLineEdit(self.gbx_columnas)
        self.txt_nombre_columna.setGeometry(QtCore.QRect(10, 46, 141, 20))
        self.txt_nombre_columna.setObjectName("txt_nombre_columna")
        self.lbl_nombre_columna = QtWidgets.QLabel(self.gbx_columnas)
        self.lbl_nombre_columna.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.lbl_nombre_columna.setObjectName("lbl_nombre_columna")
        self.lbl_tipo_dato = QtWidgets.QLabel(self.gbx_columnas)
        self.lbl_tipo_dato.setGeometry(QtCore.QRect(182, 20, 91, 16))
        self.lbl_tipo_dato.setObjectName("lbl_tipo_dato")
        self.cbx_tipo_dato = QtWidgets.QComboBox(self.gbx_columnas)
        self.cbx_tipo_dato.setGeometry(QtCore.QRect(166, 45, 101, 22))
        self.cbx_tipo_dato.setObjectName("cbx_tipo_dato")
        self.cbx_tipo_dato.addItem("")
        self.cbx_tipo_dato.addItem("")
        self.cbx_tipo_dato.addItem("")
        self.btn_abgregar_columna = QtWidgets.QPushButton(self.gbx_columnas)
        self.btn_abgregar_columna.setGeometry(QtCore.QRect(286, 45, 111, 23))
        self.btn_abgregar_columna.setObjectName("btn_abgregar_columna")
        self.btn_crear_base_datos = QtWidgets.QPushButton(Dialogo_CreacionTabla)
        self.btn_crear_base_datos.setGeometry(QtCore.QRect(224, 233, 221, 23))
        self.btn_crear_base_datos.setObjectName("btn_crear_base_datos")
        self.lbl_resultados = QtWidgets.QLabel(Dialogo_CreacionTabla)
        self.lbl_resultados.setGeometry(QtCore.QRect(30, 278, 411, 20))
        self.lbl_resultados.setText("")
        self.lbl_resultados.setObjectName("lbl_resultados")

        self.retranslateUi(Dialogo_CreacionTabla)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_CreacionTabla)

    def retranslateUi(self, Dialogo_CreacionTabla):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_CreacionTabla.setWindowTitle(_translate("Dialogo_CreacionTabla", "Creación tabla"))
        self.lbl_nombre_base_datos.setText(_translate("Dialogo_CreacionTabla", "Nombre de la base de datos:"))
        self.lbl_nombre_tabla.setText(_translate("Dialogo_CreacionTabla", "Nombre de la tabla"))
        self.gbx_columnas.setTitle(_translate("Dialogo_CreacionTabla", "Columnas:"))
        self.lbl_nombre_columna.setText(_translate("Dialogo_CreacionTabla", "Nombre columna"))
        self.lbl_tipo_dato.setText(_translate("Dialogo_CreacionTabla", "Tipo de dato"))
        self.cbx_tipo_dato.setItemText(0, _translate("Dialogo_CreacionTabla", "INTEGER"))
        self.cbx_tipo_dato.setItemText(1, _translate("Dialogo_CreacionTabla", "TEXT"))
        self.cbx_tipo_dato.setItemText(2, _translate("Dialogo_CreacionTabla", "REAL"))
        self.btn_abgregar_columna.setText(_translate("Dialogo_CreacionTabla", "Agregar columna"))
        self.btn_crear_base_datos.setText(_translate("Dialogo_CreacionTabla", "Crear Base de Datos"))
