# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_InsercionDatosBD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_InsercionDatosBD(object):
    def setupUi(self, Dialogo_InsercionDatosBD):
        Dialogo_InsercionDatosBD.setObjectName("Dialogo_InsercionDatosBD")
        Dialogo_InsercionDatosBD.resize(465, 231)
        self.widget = QtWidgets.QWidget(Dialogo_InsercionDatosBD)
        self.widget.setGeometry(QtCore.QRect(30, 20, 411, 201))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_nombre_base_datos = QtWidgets.QLabel(self.widget)
        self.lbl_nombre_base_datos.setObjectName("lbl_nombre_base_datos")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_base_datos)
        self.txt_nombre_base_datos = QtWidgets.QLineEdit(self.widget)
        self.txt_nombre_base_datos.setObjectName("txt_nombre_base_datos")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_base_datos)
        self.btn_conectar = QtWidgets.QPushButton(self.widget)
        self.btn_conectar.setObjectName("btn_conectar")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_conectar)
        spacerItem = QtWidgets.QSpacerItem(15, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.lbl_nombre_tabla = QtWidgets.QLabel(self.widget)
        self.lbl_nombre_tabla.setObjectName("lbl_nombre_tabla")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_tabla)
        self.txt_nombre_tabla = QtWidgets.QLineEdit(self.widget)
        self.txt_nombre_tabla.setObjectName("txt_nombre_tabla")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_tabla)
        self.lbl_id = QtWidgets.QLabel(self.widget)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(self.widget)
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_nombre = QtWidgets.QLabel(self.widget)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.widget)
        self.txt_nombre.setObjectName("txt_nombre")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.btn_insertar_registro = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_insertar_registro.sizePolicy().hasHeightForWidth())
        self.btn_insertar_registro.setSizePolicy(sizePolicy)
        self.btn_insertar_registro.setObjectName("btn_insertar_registro")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_insertar_registro)

        self.retranslateUi(Dialogo_InsercionDatosBD)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_InsercionDatosBD)

    def retranslateUi(self, Dialogo_InsercionDatosBD):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_InsercionDatosBD.setWindowTitle(_translate("Dialogo_InsercionDatosBD", "Insercion datos BD Sqlite"))
        self.lbl_nombre_base_datos.setText(_translate("Dialogo_InsercionDatosBD", "Nombre base de datos:"))
        self.btn_conectar.setText(_translate("Dialogo_InsercionDatosBD", "Conectar"))
        self.lbl_nombre_tabla.setText(_translate("Dialogo_InsercionDatosBD", "Nombre tabla"))
        self.lbl_id.setText(_translate("Dialogo_InsercionDatosBD", "ID:"))
        self.lbl_nombre.setText(_translate("Dialogo_InsercionDatosBD", "Nombre:"))
        self.btn_insertar_registro.setText(_translate("Dialogo_InsercionDatosBD", "Insertar Registro"))
