# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_InicioSesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_Dialogo_InicioSesion(object):
    def setupUi(self, Dialogo_InicioSesion):
        Dialogo_InicioSesion.setObjectName("Dialogo_InicioSesion")
        Dialogo_InicioSesion.resize(386, 201)
        self.lbl_titilo = QtWidgets.QLabel(Dialogo_InicioSesion)
        self.lbl_titilo.setGeometry(QtCore.QRect(120, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_titilo.setFont(font)
        self.lbl_titilo.setObjectName("lbl_titilo")
        self.lbl_correo_electronico = QtWidgets.QLabel(Dialogo_InicioSesion)
        self.lbl_correo_electronico.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.lbl_correo_electronico.setObjectName("lbl_correo_electronico")
        self.lbl_contrasea = QtWidgets.QLabel(Dialogo_InicioSesion)
        self.lbl_contrasea.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.lbl_contrasea.setObjectName("lbl_contrasea")
        self.txt_correo_electronico = QtWidgets.QLineEdit(Dialogo_InicioSesion)
        self.txt_correo_electronico.setGeometry(QtCore.QRect(150, 60, 191, 20))
        self.txt_correo_electronico.setObjectName("txt_correo_electronico")
        self.txt_contrasenia = QtWidgets.QLineEdit(Dialogo_InicioSesion)
        self.txt_contrasenia.setGeometry(QtCore.QRect(150, 100, 191, 20))
        self.txt_contrasenia.setObjectName("lbl_contrasenia")
        self.txt_contrasenia.setEchoMode(QLineEdit.Password)
        self.btn_iniciar_sesion = QtWidgets.QPushButton(Dialogo_InicioSesion)
        self.btn_iniciar_sesion.setGeometry(QtCore.QRect(150, 140, 191, 23))
        self.btn_iniciar_sesion.setObjectName("btn_iniciar_sesion")

        self.retranslateUi(Dialogo_InicioSesion)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_InicioSesion)

    def retranslateUi(self, Dialogo_InicioSesion):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_InicioSesion.setWindowTitle(_translate("Dialogo_InicioSesion", "SQLite Inicio de sesion"))
        self.lbl_titilo.setText(_translate("Dialogo_InicioSesion", "INICIO DE SESIÓN"))
        self.lbl_correo_electronico.setText(_translate("Dialogo_InicioSesion", "Correo electrónico:"))
        self.lbl_contrasea.setText(_translate("Dialogo_InicioSesion", "Contraseña:"))
        self.btn_iniciar_sesion.setText(_translate("Dialogo_InicioSesion", "Iniciar Sesión"))
