# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_BusquedaDatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_BusquedaDatos(object):
    def setupUi(self, Dialogo_BusquedaDatos):
        Dialogo_BusquedaDatos.setObjectName("Dialogo_BusquedaDatos")
        Dialogo_BusquedaDatos.resize(337, 143)
        self.layoutWidget = QtWidgets.QWidget(Dialogo_BusquedaDatos)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 271, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.txt_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_id.setObjectName("txt_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_id)
        self.lbl_nombre = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_nombre.setReadOnly(True)
        self.txt_nombre.setObjectName("txt_nombre")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_buscar.setObjectName("btn_buscar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_buscar)

        self.retranslateUi(Dialogo_BusquedaDatos)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_BusquedaDatos)

    def retranslateUi(self, Dialogo_BusquedaDatos):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_BusquedaDatos.setWindowTitle(_translate("Dialogo_BusquedaDatos", "SQLite Busqueda Informacion"))
        self.lbl_id.setText(_translate("Dialogo_BusquedaDatos", "ID:"))
        self.lbl_nombre.setText(_translate("Dialogo_BusquedaDatos", "Nombre:"))
        self.btn_buscar.setText(_translate("Dialogo_BusquedaDatos", "Buscar"))
