# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_ConsultaDatosTabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogo_ConsultaDatosTabla(object):
    def setupUi(self, Dialogo_ConsultaDatosTabla):
        Dialogo_ConsultaDatosTabla.setObjectName("Dialogo_ConsultaDatosTabla")
        Dialogo_ConsultaDatosTabla.resize(417, 348)
        self.lbl_nombre_base = QtWidgets.QLabel(Dialogo_ConsultaDatosTabla)
        self.lbl_nombre_base.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.lbl_nombre_base.setObjectName("lbl_nombre_base")
        self.lbl_nombre_tabla = QtWidgets.QLabel(Dialogo_ConsultaDatosTabla)
        self.lbl_nombre_tabla.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.lbl_nombre_tabla.setObjectName("lbl_nombre_tabla")
        self.txt_nombre_base_datos = QtWidgets.QLineEdit(Dialogo_ConsultaDatosTabla)
        self.txt_nombre_base_datos.setGeometry(QtCore.QRect(190, 30, 201, 20))
        self.txt_nombre_base_datos.setObjectName("txt_nombre_base_datos")
        self.txt_nombre_tabla = QtWidgets.QLineEdit(Dialogo_ConsultaDatosTabla)
        self.txt_nombre_tabla.setGeometry(QtCore.QRect(190, 60, 201, 20))
        self.txt_nombre_tabla.setObjectName("txt_nombre_tabla")
        self.btn_consultar_datos = QtWidgets.QPushButton(Dialogo_ConsultaDatosTabla)
        self.btn_consultar_datos.setGeometry(QtCore.QRect(190, 100, 201, 23))
        self.btn_consultar_datos.setObjectName("btn_consultar_datos")
        self.tbl_datos = QtWidgets.QTableWidget(Dialogo_ConsultaDatosTabla)
        self.tbl_datos.setGeometry(QtCore.QRect(20, 150, 371, 171))
        self.tbl_datos.setRowCount(3)
        self.tbl_datos.setColumnCount(2)
        self.tbl_datos.setObjectName("tbl_datos")

        self.retranslateUi(Dialogo_ConsultaDatosTabla)
        QtCore.QMetaObject.connectSlotsByName(Dialogo_ConsultaDatosTabla)

    def retranslateUi(self, Dialogo_ConsultaDatosTabla):
        _translate = QtCore.QCoreApplication.translate
        Dialogo_ConsultaDatosTabla.setWindowTitle(_translate("Dialogo_ConsultaDatosTabla", "Sqlite3 Consulta de Datos"))
        self.lbl_nombre_base.setText(_translate("Dialogo_ConsultaDatosTabla", "Nombre de la base de datos:"))
        self.lbl_nombre_tabla.setText(_translate("Dialogo_ConsultaDatosTabla", "Nombre tabla:"))
        self.btn_consultar_datos.setText(_translate("Dialogo_ConsultaDatosTabla", "Consultar datos"))
