# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_ReservaHotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoReservaHotel(object):
    def setupUi(self, DialogoReservaHotel):
        DialogoReservaHotel.setObjectName("DialogoReservaHotel")
        DialogoReservaHotel.resize(518, 455)
        self.lbl_fecha = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_fecha.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.lbl_fecha.setObjectName("lbl_fecha")
        self.cal_calendario = QtWidgets.QCalendarWidget(DialogoReservaHotel)
        self.cal_calendario.setGeometry(QtCore.QRect(160, 20, 312, 183))
        self.cal_calendario.setObjectName("cal_calendario")
        self.lbl_cantidad_dias = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_cantidad_dias.setGeometry(QtCore.QRect(30, 220, 121, 16))
        self.lbl_cantidad_dias.setObjectName("lbl_cantidad_dias")
        self.sbx_cantidad_dias = QtWidgets.QSpinBox(DialogoReservaHotel)
        self.sbx_cantidad_dias.setGeometry(QtCore.QRect(160, 218, 311, 22))
        self.sbx_cantidad_dias.setMinimum(1)
        self.sbx_cantidad_dias.setObjectName("sbx_cantidad_dias")
        self.lbl_tipo_habitacion = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_tipo_habitacion.setGeometry(QtCore.QRect(30, 260, 121, 16))
        self.lbl_tipo_habitacion.setObjectName("lbl_tipo_habitacion")
        self.cbx_tipo_habitacion = QtWidgets.QComboBox(DialogoReservaHotel)
        self.cbx_tipo_habitacion.setGeometry(QtCore.QRect(160, 260, 311, 22))
        self.cbx_tipo_habitacion.setObjectName("cbx_tipo_habitacion")
        self.cbx_tipo_habitacion.addItem("")
        self.cbx_tipo_habitacion.addItem("")
        self.cbx_tipo_habitacion.addItem("")
        self.lbl_tiene_mascota = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_tiene_mascota.setGeometry(QtCore.QRect(30, 306, 121, 16))
        self.lbl_tiene_mascota.setObjectName("lbl_tiene_mascota")
        self.chk_mascota = QtWidgets.QCheckBox(DialogoReservaHotel)
        self.chk_mascota.setGeometry(QtCore.QRect(160, 304, 77, 20))
        self.chk_mascota.setObjectName("chk_mascota")
        self.btn_calcular_costo = QtWidgets.QPushButton(DialogoReservaHotel)
        self.btn_calcular_costo.setGeometry(QtCore.QRect(190, 350, 151, 24))
        self.btn_calcular_costo.setObjectName("btn_calcular_costo")
        self.lbl_mostrar_total = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_mostrar_total.setGeometry(QtCore.QRect(360, 354, 111, 16))
        self.lbl_mostrar_total.setObjectName("lbl_mostrar_total")
        self.btn_reservar_y_mostrar = QtWidgets.QPushButton(DialogoReservaHotel)
        self.btn_reservar_y_mostrar.setGeometry(QtCore.QRect(30, 350, 151, 24))
        self.btn_reservar_y_mostrar.setObjectName("btn_reservar_y_mostrar")
        self.lbl_mostrar_reserva = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_mostrar_reserva.setGeometry(QtCore.QRect(120, 397, 341, 20))
        self.lbl_mostrar_reserva.setObjectName("lbl_mostrar_reserva")
        self.lbl_descripcion = QtWidgets.QLabel(DialogoReservaHotel)
        self.lbl_descripcion.setGeometry(QtCore.QRect(30, 400, 81, 16))
        self.lbl_descripcion.setObjectName("lbl_descripcion")

        self.retranslateUi(DialogoReservaHotel)
        QtCore.QMetaObject.connectSlotsByName(DialogoReservaHotel)

    def retranslateUi(self, DialogoReservaHotel):
        _translate = QtCore.QCoreApplication.translate
        DialogoReservaHotel.setWindowTitle(_translate("DialogoReservaHotel", "Dialog"))
        self.lbl_fecha.setText(_translate("DialogoReservaHotel", "Fecha de ingreso:"))
        self.lbl_cantidad_dias.setText(_translate("DialogoReservaHotel", "Cantidad de días:"))
        self.lbl_tipo_habitacion.setText(_translate("DialogoReservaHotel", "Tipo de habitación:"))
        self.cbx_tipo_habitacion.setItemText(0, _translate("DialogoReservaHotel", "Simple"))
        self.cbx_tipo_habitacion.setItemText(1, _translate("DialogoReservaHotel", "Doble"))
        self.cbx_tipo_habitacion.setItemText(2, _translate("DialogoReservaHotel", "Penhouse"))
        self.lbl_tiene_mascota.setText(_translate("DialogoReservaHotel", "Tiene mascotas ?"))
        self.chk_mascota.setText(_translate("DialogoReservaHotel", "CheckBox"))
        self.btn_calcular_costo.setText(_translate("DialogoReservaHotel", "Calcular costo"))
        self.lbl_mostrar_total.setText(_translate("DialogoReservaHotel", "TextLabel"))
        self.btn_reservar_y_mostrar.setText(_translate("DialogoReservaHotel", "Realizar reserva"))
        self.lbl_mostrar_reserva.setText(_translate("DialogoReservaHotel", ""))
        self.lbl_descripcion.setText(_translate("DialogoReservaHotel", "Descripción:"))
