# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoTiendaInformatica.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoTiendaInformatica(object):
    def setupUi(self, DialogoTiendaInformatica):
        DialogoTiendaInformatica.setObjectName("DialogoTiendaInformatica")
        DialogoTiendaInformatica.resize(537, 190)
        self.lbl_teclado = QtWidgets.QLabel(DialogoTiendaInformatica)
        self.lbl_teclado.setGeometry(QtCore.QRect(20, 35, 91, 16))
        self.lbl_teclado.setObjectName("lbl_teclado")
        self.lbl_mouse = QtWidgets.QLabel(DialogoTiendaInformatica)
        self.lbl_mouse.setGeometry(QtCore.QRect(20, 94, 81, 16))
        self.lbl_mouse.setObjectName("lbl_mouse")
        self.txt_teclado = QtWidgets.QLineEdit(DialogoTiendaInformatica)
        self.txt_teclado.setGeometry(QtCore.QRect(122, 30, 81, 22))
        self.txt_teclado.setObjectName("txt_teclado")
        self.txt_teclado.setText('0')
        self.txt_mouse = QtWidgets.QLineEdit(DialogoTiendaInformatica)
        self.txt_mouse.setGeometry(QtCore.QRect(122, 90, 81, 22))
        self.txt_mouse.setObjectName("txt_mouse")
        self.txt_mouse.setText('0')
        self.sbx_teclado = QtWidgets.QSpinBox(DialogoTiendaInformatica)
        self.sbx_teclado.setGeometry(QtCore.QRect(220, 30, 51, 22))
        self.sbx_teclado.setMinimum(1)
        self.sbx_teclado.setMaximum(45)
        self.sbx_teclado.setObjectName("sbx_teclado")
        self.sbx_mouse = QtWidgets.QSpinBox(DialogoTiendaInformatica)
        self.sbx_mouse.setEnabled(True)
        self.sbx_mouse.setGeometry(QtCore.QRect(220, 90, 51, 22))
        self.sbx_mouse.setReadOnly(False)
        self.sbx_mouse.setKeyboardTracking(True)
        self.sbx_mouse.setSuffix("")
        self.sbx_mouse.setObjectName("sbx_mouse")
        self.txt_subtotal_1 = QtWidgets.QLineEdit(DialogoTiendaInformatica)
        self.txt_subtotal_1.setGeometry(QtCore.QRect(360, 30, 131, 22))
        self.txt_subtotal_1.setObjectName("txt_subtotal_1")
        self.txt_subtotal_2 = QtWidgets.QLineEdit(DialogoTiendaInformatica)
        self.txt_subtotal_2.setGeometry(QtCore.QRect(360, 90, 131, 22))
        self.txt_subtotal_2.setObjectName("txt_subtotal_2")
        self.lbl_subtotal_1 = QtWidgets.QLabel(DialogoTiendaInformatica)
        self.lbl_subtotal_1.setGeometry(QtCore.QRect(293, 35, 55, 16))
        self.lbl_subtotal_1.setObjectName("lbl_subtotal_1")
        self.lbl_subtotal_2 = QtWidgets.QLabel(DialogoTiendaInformatica)
        self.lbl_subtotal_2.setGeometry(QtCore.QRect(293, 94, 55, 16))
        self.lbl_subtotal_2.setObjectName("lbl_subtotal_2")
        self.lbl_muestra_total = QtWidgets.QLabel(DialogoTiendaInformatica)
        self.lbl_muestra_total.setGeometry(QtCore.QRect(144, 150, 341, 20))
        self.lbl_muestra_total.setText("")
        self.lbl_muestra_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_muestra_total.setObjectName("lbl_muestra_total")

        self.retranslateUi(DialogoTiendaInformatica)
        QtCore.QMetaObject.connectSlotsByName(DialogoTiendaInformatica)

    def retranslateUi(self, DialogoTiendaInformatica):
        _translate = QtCore.QCoreApplication.translate
        DialogoTiendaInformatica.setWindowTitle(_translate("DialogoTiendaInformatica", "Tienda de Informática"))
        self.lbl_teclado.setText(_translate("DialogoTiendaInformatica", "Precio Teclado"))
        self.lbl_mouse.setText(_translate("DialogoTiendaInformatica", "Precio Mouse"))
        self.lbl_subtotal_1.setText(_translate("DialogoTiendaInformatica", "Subtotal"))
        self.lbl_subtotal_2.setText(_translate("DialogoTiendaInformatica", "Subtotal"))
