# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogo_seleccion_pais.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_SeleccionPais(object):
    def setupUi(self, Dialog_SeleccionPais):
        Dialog_SeleccionPais.setObjectName("Dialog_SeleccionPais")
        Dialog_SeleccionPais.resize(426, 136)
        self.lbl_seleccion_pais = QtWidgets.QLabel(Dialog_SeleccionPais)
        self.lbl_seleccion_pais.setGeometry(QtCore.QRect(17, 53, 111, 16))
        self.lbl_seleccion_pais.setObjectName("lbl_seleccion_pais")
        self.txt_pais = QtWidgets.QLineEdit(Dialog_SeleccionPais)
        self.txt_pais.setGeometry(QtCore.QRect(140, 49, 151, 22))
        self.txt_pais.setReadOnly(True)
        self.txt_pais.setObjectName("txt_pais")
        self.btn_seleccionar_pais = QtWidgets.QPushButton(Dialog_SeleccionPais)
        self.btn_seleccionar_pais.setGeometry(QtCore.QRect(303, 48, 111, 24))
        self.btn_seleccionar_pais.setObjectName("btn_seleccionar_pais")

        self.retranslateUi(Dialog_SeleccionPais)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SeleccionPais)

    def retranslateUi(self, Dialog_SeleccionPais):
        _translate = QtCore.QCoreApplication.translate
        Dialog_SeleccionPais.setWindowTitle(_translate("Dialog_SeleccionPais", "Dialogo Seleccionar Pais"))
        self.lbl_seleccion_pais.setText(_translate("Dialog_SeleccionPais", "Seleccione su País:"))
        self.btn_seleccionar_pais.setText(_translate("Dialog_SeleccionPais", "Seleccionar País"))
